import crypto from 'node:crypto';
const SUPABASE_URL=process.env.SUPABASE_URL||'https://vtcdwgtnwuxlmictwglk.supabase.co';
const SUPABASE_KEY=process.env.SUPABASE_PUBLISHABLE_KEY||'sb_publishable_oSvo5cig8BcmN-90GH9Oaw_4sS_AmDx';
const send=(res,s,d)=>{res.statusCode=s;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(d))};
const cookies=req=>Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return i<0?[x,'']:[x.slice(0,i),decodeURIComponent(x.slice(i+1))]}));
const read=async req=>{if(req.body&&typeof req.body==='object')return req.body;let s='';for await(const c of req)s+=c;return s?JSON.parse(s):{}};
async function user(req){const t=cookies(req).pt_access;if(!t)return null;const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${t}`}});return r.ok?{...(await r.json()),token:t}:null}
async function sb(path,{method='GET',token,data,prefer}={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{method,headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(prefer?{Prefer:prefer}:{})},body:data===undefined?undefined:JSON.stringify(data)});const out=(r.headers.get('content-type')||'').includes('json')?await r.json():await r.text();if(!r.ok)throw new Error(typeof out==='string'?out:(out.message||JSON.stringify(out)));return out}
const norm=s=>String(s||'').trim().toLowerCase().replace(/\s+/g,' ');
async function findDuplicate(d,u){
  if(d.source_message_id){
    const byMessage=await sb(`promises?source_message_id=eq.${encodeURIComponent(d.source_message_id)}&select=id,person,text,due_date,status,source`,{token:u.token});
    if(byMessage.length)return byMessage[0];
  }
  const due=d.due_date||new Date().toISOString().slice(0,10);
  const candidates=await sb(`promises?due_date=eq.${encodeURIComponent(due)}&select=id,person,text,due_date,status,source`,{token:u.token});
  const np=norm(d.person||d.from_name),nt=norm(d.text);
  return candidates.find(p=>norm(p.person)===np&&norm(p.text)===nt)||null;
}
export default async function handler(req,res){try{const u=await user(req);if(!u)return send(res,401,{error:'Authentication required'});const parts=new URL(req.url,'https://x').pathname.split('/').filter(Boolean),last=parts.at(-1);if(req.method==='GET'&&(last==='detections'||last==='list')){const rows=await sb('detections?status=eq.pending&select=*&order=detected_at.desc',{token:u.token});return send(res,200,rows)}if(req.method==='POST'&&(last==='accept'||last==='ignore')){const b=await read(req),id=String(b.id||'');if(!id)return send(res,400,{error:'Detection id required'});const rows=await sb(`detections?id=eq.${encodeURIComponent(id)}&status=eq.pending&select=*`,{token:u.token});const d=rows[0];if(!d)return send(res,404,{error:'Detection not found'});if(last==='ignore'){await sb(`detections?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',token:u.token,data:{status:'ignored',reviewed_at:new Date().toISOString()},prefer:'return=minimal'});return send(res,200,{ok:true})}
 const duplicate=await findDuplicate(d,u);if(duplicate){await sb(`detections?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',token:u.token,data:{status:'ignored',reviewed_at:new Date().toISOString()},prefer:'return=minimal'});return send(res,200,{ok:true,duplicate:true,existingPromise:duplicate,message:'This promise already exists, so no duplicate was created.'})}
 const promise={id:crypto.randomUUID(),user_id:u.id,person:d.person||d.from_name||'Email contact',text:d.text,direction:d.direction||'theirs',due_date:d.due_date||new Date().toISOString().slice(0,10),due_time:d.due_time||null,source:'Gmail',status:'open',amount:Number(d.amount||0),currency:d.currency||'INR',notes:`Detected from Gmail${d.subject?`\nSubject: ${d.subject}`:''}${d.snippet?`\nEmail: ${d.snippet}`:''}`,confidence:Number(d.confidence||0),source_message_id:d.source_message_id,updated_at:new Date().toISOString()};await sb('promises',{method:'POST',token:u.token,data:promise,prefer:'return=minimal'});await sb(`detections?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',token:u.token,data:{status:'accepted',reviewed_at:new Date().toISOString()},prefer:'return=minimal'});return send(res,200,{ok:true,promise})}return send(res,404,{error:'Detection route not found'})}catch(e){console.error(e);return send(res,500,{error:e.message||'Detection error'})}}
