const SUPABASE_URL='https://vtcdwgtnwuxlmictwglk.supabase.co';
const SUPABASE_KEY='sb_publishable_oSvo5cig8BcmN-90GH9Oaw_4sS_AmDx';
const TZ='Asia/Kolkata';
const send=(res,status,data)=>{res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(data))};
const cookies=req=>Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return i<0?[x,'']:[x.slice(0,i),decodeURIComponent(x.slice(i+1))]}));
const read=async req=>{if(req.body&&typeof req.body==='object')return req.body;let s='';for await(const c of req)s+=c;return s?JSON.parse(s):{}};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
async function authed(req){const token=cookies(req).pt_access;if(!token)return false;const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${token}`}});return r.ok}
function addDays(n){const d=new Date(today()+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}
function detectLanguage(t){if(/[\u0900-\u097F]/.test(t))return'hi';if(/\b(kal|parso|aaj|bhej|bhejunga|bhejenge|kar dunga|karunga|ho jayega|de dunga|mil jayega|lakh|hazaar|agle hafte|shaam|subah|tak|karwa dunga|confirm karunga)\b/i.test(t))return'hinglish';return'en'}
function amountOf(t){let m=t.match(/(?:₹|rs\.?|inr)\s*([\d,]+(?:\.\d+)?)/i);if(m)return Number(m[1].replace(/,/g,''));m=t.match(/([\d.]+)\s*(lakh|lac|lacs|lakhs|लाख)\b/i);if(m)return Number(m[1])*100000;m=t.match(/([\d.]+)\s*(k|thousand|hazaar|hazar|हजार)\b/i);if(m)return Number(m[1])*1000;return 0}
function dueOf(t){if(/day after tomorrow|parso|परसो/i.test(t))return addDays(2);if(/tomorrow|kal|कल/i.test(t))return addDays(1);if(/today|aaj|आज/i.test(t))return today();if(/agle hafte|next week|अगले हफ्ते|अगले सप्ताह/i.test(t))return addDays(7);return today()}
function timeOf(t){let m=t.match(/\b(\d{1,2})(?::(\d{2}))?\s*(am|pm)\b/i);if(m){let h=+m[1],mi=+(m[2]||0);if(m[3].toLowerCase()==='pm'&&h<12)h+=12;if(m[3].toLowerCase()==='am'&&h===12)h=0;return`${String(h).padStart(2,'0')}:${String(mi).padStart(2,'0')}`}m=t.match(/(?:shaam|शाम)\s*(?:ko|तक)?\s*(\d{1,2})(?::(\d{2}))?/i);if(m)return`${String((+m[1]<12?+m[1]+12:+m[1])).padStart(2,'0')}:${String(+(m[2]||0)).padStart(2,'0')}`;m=t.match(/(?:subah|सुबह)\s*(?:ko|तक)?\s*(\d{1,2})(?::(\d{2}))?/i);if(m)return`${String(+m[1]).padStart(2,'0')}:${String(+(m[2]||0)).padStart(2,'0')}`;return null}
function localExtract(message,person,direction){const lang=detectLanguage(message),promise=/\b(will|promise|send|share|pay|transfer|release|deliver|submit|confirm|call|update|bhej|bhejunga|bhejenge|karunga|kar dunga|de dunga|ho jayega|दूंगा|देंगे|भेजूंगा|भेजेंगे|करूंगा|हो जाएगा)\b/i.test(message),dueDate=dueOf(message),amount=amountOf(message),dir=direction==='mine'||direction==='theirs'?direction:/\b(i will|i'll|i’ll|we will|main|mai|hum|मैं|हम)\b/i.test(message)?'mine':'theirs',text=String(message).trim().slice(0,280),follow=lang==='hi'?`${dueDate} तक की commitment के बारे में कृपया status confirm कर दीजिए।`:lang==='hinglish'?`${dueDate} tak wali commitment ka status kindly confirm kar dijiye.`:`Just following up on the commitment due ${dueDate}. Could you please share an update?`;return{isPromise:promise,person:person||'Detected contact',text,direction:dir,dueDate,dueTime:timeOf(message),amount,currency:'INR',confidence:promise?82:25,language:lang,followUp:follow,originalMessage:message,source:'AI Inbox',notes:`Original message: ${message}\nLanguage: ${lang}\nSuggested follow-up: ${follow}`,mode:'multilingual fallback'}}
const schema={type:'object',additionalProperties:false,properties:{isPromise:{type:'boolean'},person:{type:'string'},text:{type:'string'},direction:{type:'string',enum:['mine','theirs']},dueDate:{type:['string','null']},dueTime:{type:['string','null']},amount:{type:'number'},currency:{type:'string',enum:['INR','USD','EUR','GBP']},confidence:{type:'integer',minimum:0,maximum:100},language:{type:'string',enum:['en','hi','hinglish']},followUp:{type:'string'}},required:['isPromise','person','text','direction','dueDate','dueTime','amount','currency','confidence','language','followUp']};
async function openAIExtract(message,person,direction){if(!process.env.OPENAI_API_KEY)return localExtract(message,person,direction);try{const input=`You are the commitment extraction engine for Promise Tracker. Extract ONE concrete commitment from the message. The message can be English, Hindi in Devanagari, Hinglish in Roman script, or mixed. Distinguish: (1) a real promise/commitment, (2) a request or question, (3) hedging such as try/maybe, and (4) a completed action. Only (1) should set isPromise=true. Resolve Indian expressions such as kal, parso, aaj, agle hafte, shaam/subah, lakh/hazaar, kar dunga, bhej denge, ho jayega. Current date: ${today()}; timezone: ${TZ}. Person hint: ${person||'none'}. Direction hint: ${direction||'auto'}. Preserve the message's language style in text and followUp. Message:\n${String(message).slice(0,10000)}`;const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5',input,text:{format:{type:'json_schema',name:'promise_detection',strict:true,schema}}})});const o=await r.json();if(!r.ok)throw new Error(o.error?.message||'OpenAI unavailable');const raw=o.output_text||o.output?.flatMap(x=>x.content||[]).find(x=>x.type==='output_text')?.text||'';const j=JSON.parse(raw);return{...j,source:'AI Inbox',originalMessage:message,notes:`Original message: ${message}\nLanguage: ${j.language}\nSuggested follow-up: ${j.followUp}`,mode:'OpenAI Structured Outputs'}}catch(e){console.error('OpenAI fallback',e.message);return localExtract(message,person,direction)}}
export default async function handler(req,res){try{if(req.method!=='POST')return send(res,405,{error:'Method not allowed'});if(!await authed(req))return send(res,401,{error:'Authentication required'});const b=await read(req);if(!b.message)return send(res,400,{error:'Message required'});return send(res,200,await openAIExtract(String(b.message),String(b.person||''),String(b.direction||'auto')))}catch(e){console.error(e);return send(res,500,{error:'Server error',detail:e.message})}}
