const SUPABASE_URL='https://vtcdwgtnwuxlmictwglk.supabase.co';
const SUPABASE_KEY='sb_publishable_oSvo5cig8BcmN-90GH9Oaw_4sS_AmDx';
const TZ='Asia/Kolkata';
const send=(res,status,data)=>{res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(data))};
const cookies=req=>Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return i<0?[x,'']:[x.slice(0,i),decodeURIComponent(x.slice(i+1))]}));
const read=async req=>{if(req.body&&typeof req.body==='object')return req.body;let s='';for await(const c of req)s+=c;return s?JSON.parse(s):{}};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
async function authed(req){const token=cookies(req).pt_access;if(!token)return false;const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${token}`}});return r.ok}
function addDays(n){const d=new Date(today()+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}
function nextWeekday(name){const names=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'];const map={somvar:'monday',mangalvar:'tuesday',budhvar:'wednesday',guruvar:'thursday',guruwar:'thursday',shukravar:'friday',shanivar:'saturday',ravivar:'sunday'};name=map[name]||name;const d=new Date(today()+'T12:00:00Z');const t=names.indexOf(name);let diff=(t-d.getUTCDay()+7)%7;if(!diff)diff=7;d.setUTCDate(d.getUTCDate()+diff);return d.toISOString().slice(0,10)}
function detectLanguage(t){if(/[\u0900-\u097F]/.test(t))return 'hi';if(/\b(kal|parso|aaj|bhej|bhejunga|bhejenge|kar dunga|karunga|ho jayega|ho jaega|de dunga|mil jayega|payment|paisa|paise|lakh|hazaar|agle hafte|shaam|subah|tak|karwa dunga|confirm karunga)\b/i.test(t))return 'hinglish';return 'en'}
function amountOf(t){let m=t.match(/(?:₹|rs\.?|inr)\s*([\d,]+(?:\.\d+)?)/i);if(m)return Number(m[1].replace(/,/g,''));m=t.match(/([\d.]+)\s*(lakh|lac|lacs|lakhs|लाख)\b/i);if(m)return Number(m[1])*100000;m=t.match(/([\d.]+)\s*(k|thousand|hazaar|hazar|हजार)\b/i);if(m)return Number(m[1])*1000;return 0}
function dueOf(t){const x=t.toLowerCase();if(/day after tomorrow|parso|परसो/.test(x))return addDays(2);if(/tomorrow|kal|कल/.test(x))return addDays(1);if(/today|aaj|आज/.test(x))return today();if(/agle hafte|next week|अगले हफ्ते|अगले सप्ताह/.test(x))return addDays(7);const m=x.match(/\b(monday|tuesday|wednesday|thursday|friday|saturday|sunday|somvar|mangalvar|budhvar|guruvar|guruwar|shukravar|shanivar|ravivar)\b/);return m?nextWeekday(m[1]):today()}
function timeOf(t){let m=t.match(/\b(\d{1,2})(?::(\d{2}))?\s*(am|pm)\b/i);if(m){let h=+m[1],mi=+(m[2]||0);if(m[3].toLowerCase()==='pm'&&h<12)h+=12;if(m[3].toLowerCase()==='am'&&h===12)h=0;return `${String(h).padStart(2,'0')}:${String(mi).padStart(2,'0')}`}
m=t.match(/(?:shaam|शाम)\s*(?:ko|तक)?\s*(\d{1,2})(?::(\d{2}))?/i);if(m)return `${String((+m[1]<12?+m[1]+12:+m[1])).padStart(2,'0')}:${String(+(m[2]||0)).padStart(2,'0')}`;m=t.match(/(?:subah|सुबह)\s*(?:ko|तक)?\s*(\d{1,2})(?::(\d{2}))?/i);if(m)return `${String(+m[1]).padStart(2,'0')}:${String(+(m[2]||0)).padStart(2,'0')}`;return ''}
function directionOf(t,hint){if(hint==='mine'||hint==='theirs')return hint;return /\b(i will|i'll|i’ll|we will|we'll|we’ll|main|mai|hum|मैं|हम)\b/i.test(t)?'mine':'theirs'}
function isPromise(t){return /\b(will|promise|send|share|pay|transfer|release|deliver|submit|confirm|call|update|bhej|bhejunga|bhejenge|karunga|kar dunga|karwa dunga|de dunga|ho jayega|ho jaega|mil jayega|दूंगा|देंगे|भेजूंगा|भेजेंगे|करूंगा|कर देंगे|हो जाएगा|मिल जाएगा)\b/i.test(t)}
function cleanText(t){return t.replace(/^\s*(hi|hello|hey|sir|bhai|भाई|सर)\b[^,]*,?/i,'').replace(/\b(i will|i'll|i’ll|we will|we'll|we’ll|main|mai|hum|मैं|हम)\b/i,'').trim().slice(0,280)}
function followUp(lang,person,text,due){const p=person&&person!=='Detected contact'?person:'';if(lang==='hi')return `${p?p+' जी, ':''}${text} ${due} तक करने की बात हुई थी। कृपया इसका स्टेटस कन्फर्म कर दीजिए।`;if(lang==='hinglish')return `${p?p+', ':''}${text} ${due} tak karne ki baat hui thi. Kindly iska status confirm kar dijiye.`;return `${p?p+', ':''}just following up on “${text}”, which was due ${due}. Could you please share an update?`}
function localExtract(message,person,direction){const lang=detectLanguage(message),dueDate=dueOf(message),text=cleanText(message)||message.trim(),amount=amountOf(message),dueTime=timeOf(message),dir=directionOf(message,direction),promise=isPromise(message),follow=followUp(lang,person||'Detected contact',text,dueDate);return{isPromise:promise,person:person||'Detected contact',text,direction:dir,dueDate,dueTime,amount,currency:'INR',confidence:promise?84:30,source:'AI Inbox',language:lang,originalMessage:message,followUp:follow,notes:`Original message: ${message}\nLanguage: ${lang}\nSuggested follow-up: ${follow}`,mode:'Hindi/Hinglish smart parser'}}
async function openAIExtract(message,person,direction){if(!process.env.OPENAI_API_KEY)return localExtract(message,person,direction);try{const prompt=`Extract one concrete commitment from this message. It may be English, Hindi in Devanagari, Hinglish in Roman script, or mixed. Understand Indian phrases including kal, parso, aaj, agle hafte, shaam tak, subah, lakh, hazaar, and colloquial promise forms such as kar dunga, bhej denge, ho jayega, confirm karunga. Current date ${today()}, timezone ${TZ}. Preserve the original language. Return ONLY JSON with: isPromise, person, text, direction (mine|theirs), dueDate (YYYY-MM-DD|null), dueTime (HH:MM|null), amount, currency, confidence, language (en|hi|hinglish), followUp (same language/style as message). Person hint: ${person||'none'}. Direction hint: ${direction||'auto'}. Message: ${message}`;const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5',input:prompt})});const o=await r.json();if(!r.ok)throw new Error('AI unavailable');const raw=o.output_text||o.output?.flatMap(x=>x.content||[]).map(x=>x.text||'').join('')||'';const j=JSON.parse(raw.match(/\{[\s\S]*\}/)?.[0]||'{}');return{...j,source:'AI Inbox',originalMessage:message,notes:`Original message: ${message}\nLanguage: ${j.language||detectLanguage(message)}\nSuggested follow-up: ${j.followUp||''}`,mode:'OpenAI multilingual'}}catch{return localExtract(message,person,direction)}}
export default async function handler(req,res){try{if(req.method!=='POST')return send(res,405,{error:'Method not allowed'});if(!await authed(req))return send(res,401,{error:'Authentication required'});const b=await read(req);if(!b.message)return send(res,400,{error:'Message required'});return send(res,200,await openAIExtract(String(b.message),String(b.person||''),String(b.direction||'auto')))}catch(e){console.error(e);return send(res,500,{error:'Server error',detail:e.message})}}
