const SUPABASE_URL=process.env.SUPABASE_URL||'https://vtcdwgtnwuxlmictwglk.supabase.co';
const SUPABASE_KEY=process.env.SUPABASE_PUBLISHABLE_KEY||'sb_publishable_oSvo5cig8BcmN-90GH9Oaw_4sS_AmDx';
const send=(res,status,data)=>{res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(data))};
const cookie=(n,v,age)=>`${n}=${encodeURIComponent(v)}; Path=/; HttpOnly; SameSite=Lax; Secure; Max-Age=${age}`;
const cookies=req=>Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return i<0?[x,'']:[x.slice(0,i),decodeURIComponent(x.slice(i+1))]}));
const read=async req=>{if(req.body&&typeof req.body==='object')return req.body;let s='';for await(const c of req)s+=c;return s?JSON.parse(s):{}};
const headers=(token)=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})});
async function currentUser(req,res){const c=cookies(req);let access=c.pt_access;if(access){const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:headers(access)});if(r.ok)return{user:await r.json(),access}}
 if(c.pt_refresh){const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:headers(),body:JSON.stringify({refresh_token:c.pt_refresh})});if(r.ok){const s=await r.json();res.setHeader('Set-Cookie',[cookie('pt_access',s.access_token,s.expires_in||3600),cookie('pt_refresh',s.refresh_token,2592000)]);const u=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:headers(s.access_token)});if(u.ok)return{user:await u.json(),access:s.access_token}}}
 return null}
export default async function handler(req,res){try{const action=new URL(req.url,`https://${req.headers.host||'promise-tracker-self.vercel.app'}`).pathname.split('/').filter(Boolean).pop();
 if(action==='signup'&&req.method==='POST'){const b=await read(req);if(!b.email||!b.password)return send(res,400,{error:'Email and password are required'});const r=await fetch(`${SUPABASE_URL}/auth/v1/signup`,{method:'POST',headers:headers(),body:JSON.stringify({email:String(b.email).trim(),password:String(b.password),data:{display_name:b.displayName||''}})});const o=await r.json().catch(()=>({}));if(!r.ok)return send(res,r.status,{error:o?.msg||o?.message||o?.error_description||'Could not create account'});if(o.access_token){res.setHeader('Set-Cookie',[cookie('pt_access',o.access_token,o.expires_in||3600),cookie('pt_refresh',o.refresh_token,2592000)]);return send(res,200,{user:o.user,confirmationRequired:false})}return send(res,200,{user:o.user,confirmationRequired:true})}
 if(action==='login'&&req.method==='POST'){const b=await read(req);const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:headers(),body:JSON.stringify({email:String(b.email||'').trim(),password:String(b.password||'')})});const o=await r.json().catch(()=>({}));if(!r.ok)return send(res,r.status,{error:o?.error_description||o?.msg||o?.message||'Login failed'});res.setHeader('Set-Cookie',[cookie('pt_access',o.access_token,o.expires_in||3600),cookie('pt_refresh',o.refresh_token,2592000)]);return send(res,200,{user:o.user})}
 if(action==='logout'&&req.method==='POST'){res.setHeader('Set-Cookie',[cookie('pt_access','',0),cookie('pt_refresh','',0)]);return send(res,200,{ok:true})}
 if(action==='me'&&req.method==='GET'){const s=await currentUser(req,res);if(!s)return send(res,401,{error:'Authentication required'});return send(res,200,{user:{id:s.user.id,email:s.user.email,displayName:s.user.user_metadata?.display_name||s.user.email},subscription:{plan:'free',status:'beta'}})}
 return send(res,404,{error:'Auth route not found'});
 }catch(e){console.error('auth',e);return send(res,500,{error:'Authentication service error',detail:e.message})}}
