import crypto from 'node:crypto';
const SUPABASE_URL=process.env.SUPABASE_URL||'https://vtcdwgtnwuxlmictwglk.supabase.co';
const SECRET=process.env.SUPABASE_SECRET_KEY||'';
const TZ=process.env.APP_TIMEZONE||'Asia/Kolkata';
const send=(res,s,d)=>{res.statusCode=s;res.setHeader('Content-Type','application/json');res.end(JSON.stringify(d))};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const adminHeaders=()=>({apikey:SECRET,Authorization:`Bearer ${SECRET}`,'Content-Type':'application/json'});
async function admin(path,{method='GET',data,prefer}={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{method,headers:{...adminHeaders(),...(prefer?{Prefer:prefer}:{})},body:data===undefined?undefined:JSON.stringify(data)});const out=(r.headers.get('content-type')||'').includes('json')?await r.json():await r.text();if(!r.ok)throw new Error(typeof out==='string'?out:(out.message||JSON.stringify(out)));return out}
function key(){return crypto.createHash('sha256').update(process.env.TOKEN_ENCRYPTION_KEY||'').digest()}
function decrypt(v){const[a,b,c]=String(v).split('.');const d=crypto.createDecipheriv('aes-256-gcm',key(),Buffer.from(a,'base64url'));d.setAuthTag(Buffer.from(b,'base64url'));return Buffer.concat([d.update(Buffer.from(c,'base64url')),d.final()]).toString('utf8')}
async function refresh(rt){const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET,refresh_token:rt,grant_type:'refresh_token'})});const o=await r.json();if(!r.ok)throw new Error(o.error_description||'Gmail refresh failed');return o.access_token}
function decode(s=''){try{return Buffer.from(String(s).replace(/-/g,'+').replace(/_/g,'/'),'base64').toString('utf8')}catch{return''}}
function bodyText(p){if(!p)return'';if(p.mimeType==='text/plain'&&p.body?.data)return decode(p.body.data);for(const x of p.parts||[]){const v=bodyText(x);if(v)return v}if(p.body?.data)return decode(p.body.data).replace(/<[^>]+>/g,' ');return''}
function hdr(p){return Object.fromEntries((p?.headers||[]).map(h=>[String(h.name).toLowerCase(),h.value]))}
const schema={type:'object',additionalProperties:false,properties:{isPromise:{type:'boolean'},person:{type:'string'},text:{type:'string'},direction:{type:'string',enum:['mine','theirs']},dueDate:{type:['string','null']},dueTime:{type:['string','null']},amount:{type:'number'},currency:{type:'string',enum:['INR','USD','EUR','GBP']},confidence:{type:'integer'},language:{type:'string',enum:['en','hi','hinglish']},followUp:{type:'string'}},required:['isPromise','person','text','direction','dueDate','dueTime','amount','currency','confidence','language','followUp']};
function fallback(t,person){const isPromise=/\b(will|promise|send|share|pay|transfer|release|deliver|submit|confirm|bhej|bhejunga|bhejenge|karunga|kar dunga|ho jayega|दूंगा|देंगे|भेजूंगा|भेजेंगे|करूंगा|हो जाएगा)\b/i.test(t);return{isPromise,person,text:t.slice(0,280),direction:'theirs',dueDate:null,dueTime:null,amount:0,currency:'INR',confidence:isPromise?65:15,language:/[\u0900-\u097F]/.test(t)?'hi':'en',followUp:''}}
async function extract(t,person){if(!process.env.OPENAI_API_KEY)return fallback(t,person);const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5',input:`Extract one concrete commitment from this email. It may be English, Hindi, Hinglish or mixed. Requests, questions, hedging and completed actions are not promises. Current date ${today()}, timezone ${TZ}. Sender: ${person}. Email:\n${t.slice(0,8000)}`,text:{format:{type:'json_schema',name:'promise_detection',strict:true,schema}}})});const o=await r.json();if(!r.ok)throw new Error(o.error?.message||'OpenAI failed');return JSON.parse(o.output_text||o.output?.flatMap(x=>x.content||[]).find(x=>x.type==='output_text')?.text||'{}')}
async function scan(c){const token=await refresh(decrypt(c.refresh_token_encrypted));const q=encodeURIComponent('newer_than:7d -category:promotions -category:social');const lr=await fetch(`https://gmail.googleapis.com/gmail/v1/users/me/messages?maxResults=10&q=${q}`,{headers:{Authorization:`Bearer ${token}`}}),list=await lr.json();if(!lr.ok)throw new Error(list.error?.message||'Gmail list failed');let detected=0;for(const item of list.messages||[]){const ex=await admin(`detections?user_id=eq.${c.user_id}&source=eq.Gmail&source_message_id=eq.${encodeURIComponent(item.id)}&select=id`);if(ex.length)continue;const mr=await fetch(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${item.id}?format=full`,{headers:{Authorization:`Bearer ${token}`}}),msg=await mr.json();if(!mr.ok)continue;const h=hdr(msg.payload),from=h.from||'Unknown sender',subject=h.subject||'(no subject)',body=bodyText(msg.payload),content=`Subject: ${subject}\nFrom: ${from}\n\n${body||msg.snippet||''}`;let x;try{x=await extract(content,from)}catch{x=fallback(content,from)}if(!x.isPromise||x.confidence<55)continue;await admin('detections',{method:'POST',prefer:'return=minimal',data:{user_id:c.user_id,source:'Gmail',source_message_id:item.id,source_thread_id:item.threadId,subject,from_name:from,snippet:(msg.snippet||body).slice(0,500),person:x.person||from,text:x.text,direction:x.direction||'theirs',due_date:x.dueDate||null,due_time:x.dueTime||null,amount:Number(x.amount||0),currency:x.currency||'INR',confidence:Number(x.confidence||0),status:'pending'}});detected++}await admin(`gmail_connections?user_id=eq.${c.user_id}`,{method:'PATCH',data:{last_scan_at:new Date().toISOString(),last_scan_error:null,updated_at:new Date().toISOString()},prefer:'return=minimal'});return detected}
export default async function handler(req,res){try{if(!process.env.CRON_SECRET||req.headers.authorization!==`Bearer ${process.env.CRON_SECRET}`)return send(res,401,{error:'Unauthorized'});if(!SECRET||!process.env.GOOGLE_CLIENT_ID||!process.env.GOOGLE_CLIENT_SECRET||!process.env.TOKEN_ENCRYPTION_KEY)return send(res,503,{error:'Gmail auto scan is not configured'});const connections=await admin('gmail_connections?scan_enabled=eq.true&select=*&limit=20');const results=[];for(const c of connections){try{results.push({user_id:c.user_id,detected:await scan(c)})}catch(e){await admin(`gmail_connections?user_id=eq.${c.user_id}`,{method:'PATCH',data:{last_scan_error:e.message,updated_at:new Date().toISOString()},prefer:'return=minimal'});results.push({user_id:c.user_id,error:e.message})}}return send(res,200,{ok:true,users:results.length,results})}catch(e){console.error(e);return send(res,500,{error:e.message||'Cron error'})}}
