import crypto from 'node:crypto';

const SUPABASE_URL=process.env.SUPABASE_URL||'https://vtcdwgtnwuxlmictwglk.supabase.co';
const SUPABASE_KEY=process.env.SUPABASE_PUBLISHABLE_KEY||'sb_publishable_oSvo5cig8BcmN-90GH9Oaw_4sS_AmDx';
const SECRET=process.env.SUPABASE_SECRET_KEY||'';
const BASE=process.env.APP_BASE_URL||'https://promise-tracker-self.vercel.app';
const REDIRECT=process.env.GOOGLE_REDIRECT_URI||`${BASE}/api/gmail/callback`;
const TZ=process.env.APP_TIMEZONE||'Asia/Kolkata';
const configured=()=>Boolean(process.env.GOOGLE_CLIENT_ID&&process.env.GOOGLE_CLIENT_SECRET&&SECRET&&process.env.TOKEN_ENCRYPTION_KEY&&process.env.OAUTH_STATE_SECRET);
const send=(res,s,d)=>{res.statusCode=s;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(d))};
const cookies=req=>Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return i<0?[x,'']:[x.slice(0,i),decodeURIComponent(x.slice(i+1))]}));
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const sbHeaders=(token)=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})});
async function authUser(req){const token=cookies(req).pt_access;if(!token)return null;const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:sbHeaders(token)});return r.ok?await r.json():null}
function adminHeaders(){return{apikey:SECRET,Authorization:`Bearer ${SECRET}`,'Content-Type':'application/json'}}
async function admin(path,{method='GET',data,prefer}={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{method,headers:{...adminHeaders(),...(prefer?{Prefer:prefer}:{})},body:data===undefined?undefined:JSON.stringify(data)});const out=(r.headers.get('content-type')||'').includes('json')?await r.json():await r.text();if(!r.ok)throw new Error(typeof out==='string'?out:(out.message||JSON.stringify(out)));return out}
function key(){return crypto.createHash('sha256').update(process.env.TOKEN_ENCRYPTION_KEY||'').digest()}
function encrypt(text){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key(),iv);const enc=Buffer.concat([c.update(text,'utf8'),c.final()]);return [iv.toString('base64url'),c.getAuthTag().toString('base64url'),enc.toString('base64url')].join('.')}
function decrypt(v){const[a,b,c]=String(v).split('.');const d=crypto.createDecipheriv('aes-256-gcm',key(),Buffer.from(a,'base64url'));d.setAuthTag(Buffer.from(b,'base64url'));return Buffer.concat([d.update(Buffer.from(c,'base64url')),d.final()]).toString('utf8')}
function signState(userId){const ts=Date.now(),body=`${userId}.${ts}`,sig=crypto.createHmac('sha256',process.env.OAUTH_STATE_SECRET).update(body).digest('base64url');return Buffer.from(`${body}.${sig}`).toString('base64url')}
function verifyState(state){try{const raw=Buffer.from(state,'base64url').toString(),[uid,ts,sig]=raw.split('.');if(Date.now()-Number(ts)>15*60*1000)return null;const body=`${uid}.${ts}`,want=crypto.createHmac('sha256',process.env.OAUTH_STATE_SECRET).update(body).digest('base64url');return crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(want))?uid:null}catch{return null}}
async function refresh(refreshToken){const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET,refresh_token:refreshToken,grant_type:'refresh_token'})});const o=await r.json();if(!r.ok)throw new Error(o.error_description||'Could not refresh Gmail access');return o.access_token}
function decode(s=''){try{return Buffer.from(String(s).replace(/-/g,'+').replace(/_/g,'/'),'base64').toString('utf8')}catch{return''}}
function bodyText(payload){if(!payload)return'';if(payload.mimeType==='text/plain'&&payload.body?.data)return decode(payload.body.data);for(const p of payload.parts||[]){const x=bodyText(p);if(x)return x}if(payload.body?.data)return decode(payload.body.data).replace(/<[^>]+>/g,' ');return''}
function headers(payload){return Object.fromEntries((payload?.headers||[]).map(h=>[String(h.name).toLowerCase(),h.value]))}
function addDays(n){const d=new Date(today()+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}
function senderName(from=''){return String(from).replace(/<[^>]+>/g,'').replace(/^['\"]|['\"]$/g,'').trim()||String(from)}
function isTransactional(subject='',from='',body=''){const s=`${subject}\n${from}\n${body.slice(0,1200)}`.toLowerCase();return /\b(usage alert|billing alert|payment received|payment successful|transaction alert|receipt|invoice|otp|one[- ]time password|verification code|login alert|security alert|statement|order confirmation|delivery update|subscription|newsletter|promotional|you(?:'|’)ve spent|you have spent|amount debited|amount credited)\b/i.test(s)||/notifications?@|no[-_.]?reply@|noreply@/i.test(from)}
function cleanPromiseText(t=''){return String(t).replace(/^subject:.*?\n/i,'').replace(/^from:.*?\n/i,'').replace(/\s+/g,' ').trim().slice(0,180)}
function fallback(message,person=''){const t=String(message||'').trim(),lang=/[\u0900-\u097F]/.test(t)?'hi':/\b(kal|parso|aaj|bhej|kar dunga|karunga|ho jayega|lakh|hazaar|agle hafte|shaam|subah|tak)\b/i.test(t)?'hinglish':'en';const promise=/\b(i will|we will|i'll|we'll|promise|send|share|pay|transfer|release|deliver|submit|confirm|call|update|bhejunga|bhejenge|karunga|kar dunga|de dunga|दूंगा|देंगे|भेजूंगा|भेजेंगे|करूंगा)\b/i.test(t);let due=today();if(/parso|परसो|day after tomorrow/i.test(t))due=addDays(2);else if(/kal|कल|tomorrow/i.test(t))due=addDays(1);let m=t.match(/([\d.]+)\s*(lakh|lac|lakhs|लाख)\b/i),amount=m?Number(m[1])*100000:0;if(!amount){m=t.match(/(?:₹|rs\.?|inr)\s*([\d,]+)/i);amount=m?Number(m[1].replace(/,/g,'')):0}return{isPromise:promise,person:senderName(person)||'Email contact',text:cleanPromiseText(t),direction:'theirs',dueDate:due,dueTime:null,amount,currency:'INR',confidence:promise?68:20,language:lang,followUp:lang==='hi'?`नमस्कार, ${due} तक की commitment के बारे में कृपया status confirm कर दीजिए।`:lang==='hinglish'?`Hi, ${due} tak wali commitment ka status kindly confirm kar dijiye.`:`Hi, just following up on the commitment due ${due}. Could you please share an update?`}}
async function extract(message,person){if(!process.env.OPENAI_API_KEY)return fallback(message,person);const schema={type:'object',additionalProperties:false,properties:{isPromise:{type:'boolean'},person:{type:'string'},text:{type:'string'},direction:{type:'string',enum:['mine','theirs']},dueDate:{type:['string','null']},dueTime:{type:['string','null']},amount:{type:'number'},currency:{type:'string',enum:['INR','USD','EUR','GBP']},confidence:{type:'integer'},language:{type:'string',enum:['en','hi','hinglish']},followUp:{type:'string'}},required:['isPromise','person','text','direction','dueDate','dueTime','amount','currency','confidence','language','followUp']};
 const input=`Extract one concrete interpersonal commitment from this email. It may be English, Hindi, Hinglish, or mixed. A commitment means a person explicitly promises or commits to do something in the future. Reject requests, reminders, intentions, completed actions, receipts, invoices, billing/usage alerts, bank alerts, OTPs, newsletters, system notifications, order/delivery updates and automated emails. The text field must be a short clean summary of only the commitment (max 140 characters), never include Subject:, From:, email addresses, signatures, or quoted email headers. Person should be a human-readable name, not an email address when a name is available. Current date: ${today()}; timezone: ${TZ}. Sender/person hint: ${person}. Email:\n${message.slice(0,8000)}`;
 const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5',input,text:{format:{type:'json_schema',name:'promise_detection',strict:true,schema}}})});const o=await r.json();if(!r.ok)throw new Error(o.error?.message||'OpenAI extraction failed');const raw=o.output_text||o.output?.flatMap(x=>x.content||[]).find(x=>x.type==='output_text')?.text||'';const j=JSON.parse(raw);j.text=cleanPromiseText(j.text);j.person=senderName(j.person||person);return j}
async function scanUser(userId){const con=(await admin(`gmail_connections?user_id=eq.${encodeURIComponent(userId)}&select=*`))[0];if(!con)return{connected:false,scanned:0,detected:0};const token=await refresh(decrypt(con.refresh_token_encrypted));const q=encodeURIComponent('newer_than:14d -category:promotions -category:social');const lr=await fetch(`https://gmail.googleapis.com/gmail/v1/users/me/messages?maxResults=12&q=${q}`,{headers:{Authorization:`Bearer ${token}`}});const list=await lr.json();if(!lr.ok)throw new Error(list.error?.message||'Gmail list failed');let detected=0,scanned=0;for(const item of list.messages||[]){scanned++;const existing=await admin(`detections?user_id=eq.${encodeURIComponent(userId)}&source=eq.Gmail&source_message_id=eq.${encodeURIComponent(item.id)}&select=id`);if(existing.length)continue;const mr=await fetch(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${item.id}?format=full`,{headers:{Authorization:`Bearer ${token}`}});const msg=await mr.json();if(!mr.ok)continue;const h=headers(msg.payload),from=h.from||'Unknown sender',subject=h.subject||'(no subject)',body=bodyText(msg.payload).slice(0,12000);if(isTransactional(subject,from,body||msg.snippet||''))continue;const combined=`Subject: ${subject}\nFrom: ${from}\n\n${body||msg.snippet||''}`;let x;try{x=await extract(combined,from)}catch{x=fallback(combined,from)}if(!x.isPromise||x.confidence<60||!x.text)continue;await admin('detections',{method:'POST',prefer:'return=minimal',data:{user_id:userId,source:'Gmail',source_message_id:item.id,source_thread_id:item.threadId,subject,from_name:from,snippet:(msg.snippet||body).slice(0,500),person:x.person||senderName(from),text:cleanPromiseText(x.text),direction:x.direction||'theirs',due_date:x.dueDate||null,due_time:x.dueTime||null,amount:Number(x.amount||0),currency:x.currency||'INR',confidence:Number(x.confidence||0),status:'pending'}});detected++}await admin(`gmail_connections?user_id=eq.${encodeURIComponent(userId)}`,{method:'PATCH',prefer:'return=minimal',data:{last_scan_at:new Date().toISOString(),last_scan_error:null,updated_at:new Date().toISOString()}});return{connected:true,scanned,detected}}

export default async function handler(req,res){try{const path=new URL(req.url,BASE).pathname.split('/').filter(Boolean).pop();if(path==='callback'){if(!configured())return res.writeHead(302,{Location:`${BASE}/?gmail=not-configured`}).end();const u=new URL(req.url,BASE),uid=verifyState(u.searchParams.get('state')||'');if(!uid)return res.writeHead(302,{Location:`${BASE}/?gmail=invalid-state`}).end();const current=await authUser(req);if(!current||current.id!==uid)return res.writeHead(302,{Location:`${BASE}/?gmail=login-required`}).end();const code=u.searchParams.get('code');const tr=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET,redirect_uri:REDIRECT,grant_type:'authorization_code'})});const tok=await tr.json();if(!tr.ok||!tok.refresh_token)return res.writeHead(302,{Location:`${BASE}/?gmail=token-error`}).end();const pr=await fetch('https://gmail.googleapis.com/gmail/v1/users/me/profile',{headers:{Authorization:`Bearer ${tok.access_token}`}});const prof=await pr.json();await admin('gmail_connections',{method:'POST',prefer:'resolution=merge-duplicates,return=minimal',data:{user_id:uid,gmail_email:prof.emailAddress||current.email,refresh_token_encrypted:encrypt(tok.refresh_token),scan_enabled:true,updated_at:new Date().toISOString()}});return res.writeHead(302,{Location:`${BASE}/?gmail=connected`}).end()}
 const user=await authUser(req);if(!user)return send(res,401,{error:'Authentication required'});if(path==='status'){if(!configured())return send(res,200,{configured:false,connected:false});const c=await admin(`gmail_connections?user_id=eq.${user.id}&select=gmail_email,scan_enabled,last_scan_at,last_scan_error`);return send(res,200,{configured:true,connected:Boolean(c.length),...(c[0]||{})})}
 if(path==='connect'){if(!configured())return send(res,503,{error:'Gmail credentials are not configured on the server'});const auth=new URL('https://accounts.google.com/o/oauth2/v2/auth');auth.search=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,redirect_uri:REDIRECT,response_type:'code',scope:'https://www.googleapis.com/auth/gmail.readonly',access_type:'offline',prompt:'consent',include_granted_scopes:'true',state:signState(user.id)}).toString();return res.writeHead(302,{Location:auth.toString()}).end()}
 if(path==='scan'&&req.method==='POST'){if(!configured())return send(res,503,{error:'Gmail is not configured'});return send(res,200,await scanUser(user.id))}
 if(path==='disconnect'&&req.method==='POST'){if(!configured())return send(res,200,{ok:true});await admin(`gmail_connections?user_id=eq.${user.id}`,{method:'DELETE',prefer:'return=minimal'});return send(res,200,{ok:true})}
 return send(res,404,{error:'Gmail route not found'})}catch(e){console.error(e);return send(res,500,{error:e.message||'Gmail error'})}}
