import crypto from 'node:crypto';

const SUPABASE_URL = process.env.SUPABASE_URL || 'https://vtcdwgtnwuxlmictwglk.supabase.co';
const SUPABASE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY || 'sb_publishable_oSvo5cig8BcmN-90GH9Oaw_4sS_AmDx';
const tz = process.env.APP_TIMEZONE || 'Asia/Kolkata';
const now = () => new Date().toISOString();
const today = () => new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const send=(res,status,data,headers={})=>{res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');for(const[k,v]of Object.entries(headers))res.setHeader(k,v);res.end(JSON.stringify(data))};
const cookie=(n,v,age)=>`${n}=${encodeURIComponent(v)}; Path=/; HttpOnly; SameSite=Lax; Secure; Max-Age=${age}`;
const cookies=req=>Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return i<0?[x,'']:[x.slice(0,i),decodeURIComponent(x.slice(i+1))]}));
const read=async req=>{if(req.body&&typeof req.body==='object')return req.body;let s='';for await(const c of req)s+=c;if(!s)return{};return JSON.parse(s)};
const sbHeaders=(token)=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})});
async function sfetch(path,{method='GET',token,data,prefer}={}){const r=await fetch(`${SUPABASE_URL}${path}`,{method,headers:{...sbHeaders(token),...(prefer?{Prefer:prefer}:{})},body:data===undefined?undefined:JSON.stringify(data)});const ct=r.headers.get('content-type')||'';const out=ct.includes('json')?await r.json():await r.text();if(!r.ok)throw Object.assign(new Error(out?.message||out?.msg||out?.error_description||String(out)),{status:r.status});return out}
async function userFrom(req,res){const c=cookies(req);let token=c.pt_access,user=null;if(token){try{user=await sfetch('/auth/v1/user',{token})}catch{}}if(!user&&c.pt_refresh){try{const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:sbHeaders(),body:JSON.stringify({refresh_token:c.pt_refresh})});if(r.ok){const s=await r.json();token=s.access_token;user=await sfetch('/auth/v1/user',{token});res.setHeader('Set-Cookie',[cookie('pt_access',s.access_token,s.expires_in||3600),cookie('pt_refresh',s.refresh_token,2592000)])}}catch{}}return user?{...user,token}:null}
function heuristic(message,person='',direction='auto'){const t=String(message||'').trim();let dir=direction;if(dir==='auto')dir=/\b(i will|i'll|i’ll|we will|we'll|we’ll)\b/i.test(t)?'mine':'theirs';const mm=t.match(/(?:₹|rs\.?|inr)\s*([\d,]+(?:\.\d+)?)/i);const amount=mm?Number(mm[1].replace(/,/g,'')):0;const d=new Date(today()+'T12:00:00Z');let due=today();if(/day after tomorrow/i.test(t)){d.setUTCDate(d.getUTCDate()+2);due=d.toISOString().slice(0,10)}else if(/tomorrow/i.test(t)){d.setUTCDate(d.getUTCDate()+1);due=d.toISOString().slice(0,10)}const day=t.match(/\b(monday|tuesday|wednesday|thursday|friday|saturday|sunday)\b/i);if(day){const names=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'],target=names.indexOf(day[1].toLowerCase());let diff=(target-d.getUTCDay()+7)%7;if(!diff)diff=7;d.setUTCDate(d.getUTCDate()+diff);due=d.toISOString().slice(0,10)}const tm=t.match(/\b(\d{1,2})(?::(\d{2}))?\s*(am|pm)\b/i);let dueTime='';if(tm){let h=+tm[1],m=+(tm[2]||0);if(tm[3].toLowerCase()==='pm'&&h<12)h+=12;if(tm[3].toLowerCase()==='am'&&h===12)h=0;dueTime=`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`}const isPromise=/\b(will|i'll|i’ll|we'll|we’ll|promise|confirm|send|share|pay|transfer|release|deliver|submit|update|call|meet)\b/i.test(t);let text=t.replace(/^\s*(hi|hello|hey)\b[^,]*,?/i,'').replace(/\b(i will|i'll|i’ll|we will|we'll|we’ll|will)\b/i,'').trim();return{isPromise,person:person||'Detected contact',text:(text||t).slice(0,280),direction:dir,dueDate:due,dueTime,amount,currency:'INR',confidence:isPromise?72:25,source:'AI Inbox',mode:'smart fallback'}}
async function aiExtract(message,person,direction){if(!process.env.OPENAI_API_KEY)return heuristic(message,person,direction);try{const prompt=`Extract one concrete promise from this message. Current date ${today()} timezone ${tz}. Return only JSON with isPromise boolean, person string, text string, direction mine|theirs, dueDate YYYY-MM-DD|null, dueTime HH:MM|null, amount number, currency INR|USD|EUR|GBP, confidence 0-100. Person hint: ${person||'none'}. Direction hint: ${direction||'auto'}. Message: ${message}`;const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5',input:prompt})});const o=await r.json();if(!r.ok)throw new Error('AI unavailable');const txt=o.output_text||o.output?.flatMap(x=>x.content||[]).map(x=>x.text||'').join('')||'';const j=JSON.parse(txt.match(/\{[\s\S]*\}/)?.[0]||'{}');return{...j,source:'AI Inbox',mode:'OpenAI'}}catch{return heuristic(message,person,direction)}}

export default async function handler(req,res){try{const method=req.method||'GET';const url=new URL(req.url,`https://${req.headers.host||'promise-tracker.vercel.app'}`);const p=url.pathname;
 if(p==='/api/config')return send(res,200,{version:'3.1-beta',cloudEnabled:true,openaiConfigured:Boolean(process.env.OPENAI_API_KEY),googleAuthConfigured:false,gmailConfigured:false,billingConfigured:false,whatsappConfigured:false,timezone:tz});
 if(p==='/api/auth/signup'&&method==='POST'){const b=await read(req);const r=await fetch(`${SUPABASE_URL}/auth/v1/signup`,{method:'POST',headers:sbHeaders(),body:JSON.stringify({email:b.email,password:b.password,data:{display_name:b.displayName||''}})});const o=await r.json();if(!r.ok)return send(res,r.status,{error:o?.msg||o?.message||'Signup failed'});if(o.access_token){res.setHeader('Set-Cookie',[cookie('pt_access',o.access_token,o.expires_in||3600),cookie('pt_refresh',o.refresh_token,2592000)]);return send(res,200,{user:o.user})}return send(res,200,{user:o.user,confirmationRequired:true})}
 if(p==='/api/auth/login'&&method==='POST'){const b=await read(req);const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:sbHeaders(),body:JSON.stringify({email:b.email,password:b.password})});const o=await r.json();if(!r.ok)return send(res,r.status,{error:o?.error_description||o?.msg||'Login failed'});res.setHeader('Set-Cookie',[cookie('pt_access',o.access_token,o.expires_in||3600),cookie('pt_refresh',o.refresh_token,2592000)]);return send(res,200,{user:o.user})}
 if(p==='/api/auth/logout'&&method==='POST'){res.setHeader('Set-Cookie',[cookie('pt_access','',0),cookie('pt_refresh','',0)]);return send(res,200,{ok:true})}
 const user=await userFrom(req,res);if(!user)return send(res,401,{error:'Authentication required'});
 if(p==='/api/auth/me')return send(res,200,{user:{id:user.id,email:user.email,displayName:user.user_metadata?.display_name||user.email},subscription:{plan:'free',status:'beta'}});
 if(p==='/api/promises'&&method==='GET'){const rows=await sfetch('/rest/v1/promises?select=*&order=due_date.asc,created_at.desc',{token:user.token});return send(res,200,rows)}
 if(p==='/api/promises'&&method==='POST'){const b=await read(req);const item={id:crypto.randomUUID(),user_id:user.id,person:String(b.person||'Unknown').trim(),text:String(b.text||'').trim(),direction:b.direction==='mine'?'mine':'theirs',due_date:String(b.dueDate||b.due_date||today()).slice(0,10),due_time:(b.dueTime||b.due_time||null)||null,source:String(b.source||'Manual'),status:'open',amount:Number(b.amount||0),currency:['INR','USD','EUR','GBP'].includes(b.currency)?b.currency:'INR',notes:String(b.notes||''),confidence:Number(b.confidence||100),updated_at:now()};if(!item.text)return send(res,400,{error:'Promise text is required'});const rows=await sfetch('/rest/v1/promises',{method:'POST',token:user.token,data:item,prefer:'return=representation'});return send(res,201,rows[0])}
 const m=p.match(/^\/api\/promises\/([^/]+)$/);if(m&&method==='PUT'){const b=await read(req);const data={person:b.person,text:b.text,direction:b.direction,due_date:b.dueDate||b.due_date,due_time:(b.dueTime||b.due_time||null)||null,source:b.source,status:b.status,amount:Number(b.amount||0),currency:b.currency||'INR',notes:b.notes||'',updated_at:now()};Object.keys(data).forEach(k=>data[k]===undefined&&delete data[k]);const rows=await sfetch(`/rest/v1/promises?id=eq.${encodeURIComponent(m[1])}`,{method:'PATCH',token:user.token,data,prefer:'return=representation'});return send(res,200,rows[0]||{})}if(m&&method==='DELETE'){await sfetch(`/rest/v1/promises?id=eq.${encodeURIComponent(m[1])}`,{method:'DELETE',token:user.token,prefer:'return=minimal'});return send(res,200,{ok:true})}
 if(p==='/api/ai/extract'&&method==='POST'){const b=await read(req);if(!b.message)return send(res,400,{error:'Message required'});return send(res,200,await aiExtract(b.message,b.person||'',b.direction||'auto'))}
 if(p==='/api/billing/status')return send(res,200,{plan:'free',status:'beta',configured:false});
 if(p==='/api/detections')return send(res,200,[]);if(p==='/api/notifications')return send(res,200,[]);if(p==='/api/integrations/gmail/status')return send(res,200,{configured:false,connected:false});if(p==='/api/integrations/whatsapp/status')return send(res,200,{configured:false,connected:false});
 return send(res,404,{error:'API route not found'});
}catch(e){console.error(e);return send(res,e.status||500,{error:e.status?e.message:'Server error',detail:e.message})}}
